FROM python:3.10.12-slim-bullseye

RUN apt-get update && apt-get install -y gcc g++ mpich libmpich-dev

WORKDIR /app

COPY ./start.sh /usr/bin/start.sh

RUN pip install elasticsearch confluent_kafka && mkdir -p /usr/bin/

COPY . .

RUN mpicc -fopenmp -o teste jogodavida_mpi_omp.c

RUN chmod +x /usr/bin/start.sh

ENTRYPOINT [ "start.sh" ]
