FROM python:3.10.12-slim-bullseye

RUN apt-get update && apt-get install -y gcc g++ mpich libmpich-dev && mkdir -p /usr/bin/
COPY ./start.sh /usr/bin/start.sh

WORKDIR /app


RUN pip install elasticsearch confluent_kafka

COPY . .

RUN mpicc -fopenmp -o teste jogodavida_mpi_omp.c

RUN chmod +x /usr/bin/start.sh

ENTRYPOINT [ "start.sh" ]
